config/routes.rb
Rails.application.routes.draw do

  get 'pour-over', to: 'home#pour_over'
  get 'pet', to: 'home#pet'
  get 'formula', to: 'home#formula'
  get 'legal', to: 'home#legal'

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :emails, only: [:create]
    end
  end

  root 'home#home'

end

app/models/email.rb
class Email < ActiveRecord::Base

  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

end

app/controllers/api/v1/emails_controller.rb
module Api
  module V1
    class EmailsController < QuirkyApi::Base
      def create
        @email = Email.where(email: params[:email]).first_or_initialize
        @email.save!
        respond_with(email: @email.email)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  # before_action :authenticate

  def authenticate
    return unless Rails.env == 'production'
    authenticate_or_request_with_http_basic do |username, password|
      username == "poppy" && password == "doitlive"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :check_caching

  def formula
    @title = "Formula"
  end

  def home
    @title = "We make smart, beautifully designed products that think for you."
  end

  def legal
    @title = "Legal"
  end

  def pet
    @title = "Pet"
  end

  def pour_over
    @title = "Pour-Over"
  end

  protected

  def check_caching
    set_cache_control_headers if ENV['SET_CACHE_CONTROL_HEADERS'] == "true"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<script type="text/javascript">
  init_home_js();
</script>

<section class="popup-video">


  <div class="width">
  <svg id="close" xmlns="http://www.w3.org/2000/svg" viewBox="39.2 22.3 25 24.5">
<path d="M39.5,46.4c0.2,0.2,0.6,0.4,0.9,0.4c0.3,0,0.6-0.1,0.9-0.4l10.3-10.3L62,46.4c0.2,0.2,0.6,0.4,0.9,0.4
  c0.3,0,0.6-0.1,0.9-0.4c0.5-0.5,0.5-1.3,0-1.8L53.5,34.3l9.8-9.8c0.5-0.5,0.5-1.3,0-1.8c-0.5-0.5-1.3-0.5-1.8,0l-9.8,9.8l-9.8-9.8
  c-0.5-0.5-1.3-0.5-1.8,0c-0.5,0.5-0.5,1.3,0,1.8l9.8,9.8L39.5,44.6C39,45.1,39,45.9,39.5,46.4z"/>
</svg>



    <iframe id="pop" src="//player.vimeo.com/video/123626425?api=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

  </div>
</section>


<!-- Full Screen Video -->
<section id="header-video">
  <a id="mobile-menu"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30.8 20"><path d="M30,18.5H0.8c-0.5,0-0.8,0.3-0.8,0.8C0,19.7,0.3,20,0.8,20H30c0.5,0,0.8-0.3,0.8-0.8C30.8,18.8,30.5,18.5,30,18.5z"/><path d="M0.8,1.5H30c0.5,0,0.8-0.3,0.8-0.8S30.5,0,30,0H0.8C0.3,0,0,0.3,0,0.8S0.3,1.5,0.8,1.5z"/><path d="M30,9.2H0.8C0.3,9.2,0,9.5,0,10c0,0.5,0.3,0.8,0.8,0.8H30c0.5,0,0.8-0.3,0.8-0.8C30.8,9.5,30.5,9.2,30,9.2z"/></svg></a>
  <%= image_tag "poppy.png", id: "footer-products", class: "logo animated fadeIn" %>
  <span class="play-icon animated fadeIn"></span>
  <%= image_tag "down.png", id: "footer-products", class: "down animated fadeIn" %>
</section>


<!-- Our Products -->
<section id="our-products" class="section">
  <div id="coming-soon">
      <h1>We make smart, beautifully designed products that think for you.</h1>
      <p>They’re not just connected—they’re truly thoughtful. They anticipate your needs <br>and make intelligent decisions to keep your family happy and healthy.</p>
      <span class="coming-in" id="product-scroll-target">Coming late 2015</span>
  </div>

  <div id="product-boxes">
    <div class="width-wrapper">

      <div class="product-box">
        <a href="<%= pour_over_path %>">
          <%= image_tag "coffee.jpg", id: "footer-products", alt: "coffee" %>
          <h2>Pour-Over</h2>
          <span class="go">Go</span>
        </a>
      </div>

      <div class="product-box">
        <a href="<%= formula_path %>">
          <%= image_tag "formula.jpg", id: "footer-products", alt: "formula" %>
          <h2>Formula</h2>
          <span class="go">Go</span>
        </a>
      </div>

      <div class="product-box">
        <a href="<%= pet_path %>">
          <%= image_tag "pet.jpg", id: "footer-products", alt: "pet" %>
          <h2>Pet</h2>
          <span class="go">Go</span>
        </a>
      </div>

    </div>
  </div>
</section>


<!-- Pour Over -->
<section id="pour-over-h" class="product">
  <div class="width-wrapper">
    <%= image_tag "coffee_video.jpg", class: "video_static", alt: "coffee" %>
    <div class="product-text">

      <video id="pour-over-video">
          <source src="<%= asset_path "pour-over2.mp4" %>" type="video/mp4" />
          <source src="<%= asset_path "pour-over2.webm" %>" type="video/webm" />
          <source src="<%= asset_path "pour-over2.ogv" %>" type="video/ogg" />
      </video>
      <h1>Pour-Over</h1>
      <h2>smart artisanal coffee machine</h2>
      <p>We carefully handcrafted this machine in San Francisco, a city that’s perfected the pour-over, because we understand the importance of a truly outstanding cup. It’s the world’s first fully automatic pour-over coffee maker, designed to recreate the boutique brewing experience in your home.</p>
      <a href="<%= pour_over_path %>" class="learn-more">Learn More</a>





    </div>
  </div>
</section>

<!-- Formula -->
<section id="formula-h" class="product">
  <div class="width-wrapper cf">
    <%= image_tag "formula_video.jpg", class: "video_static", alt: "formula" %>
    <div class="product-text">
      <h1>Formula</h1>
      <h2>smart infant formula machine</h2>
      <p>Nobody said new parenthood was easy—until now. While others stress over feedings, you'll be worry-free with Poppy Formula. Providing peace of mind and a much-needed extra set of hands, it prepares bottles quickly and at just the right temperature with simple, one-handed operation.</p>
      <a href="<%= formula_path %>" class="learn-more">Learn More</a>
            <video id="formula-video">
          <source src="<%= asset_path "formula.mp4" %>" type="video/mp4" />
          <source src="<%= asset_path "formula.webm" %>" type="video/webm" />
          <source src="<%= asset_path "formula.ogv" %>" type="video/ogg" />
      </video>
    </div>

  </div>
</section>

<!-- Pet -->
<section id="pet-h" class="product">
  <div class="width-wrapper">
    <%= image_tag "pet_video.jpg", class: "video_static", alt: "pet" %>
    <div class="product-text">
      <h1>Pet</h1>
      <h2>smart pet feeder</h2>
      <p>A feeder that actually thinks about your animal’s needs, Poppy Pet takes the guesswork out of pet care. Track when your furry friend eats and how much is left in the bowl, schedule meals on the go, and get automatic refills on food when the storage container detects that you’re running low.</p>
      <a href="<%= pet_path %>" class="learn-more">Learn More</a>
    </div>
        <video id="pet-video">
          <source src="<%= asset_path "pet.mp4" %>" type="video/mp4" />
          <source src="<%= asset_path "pet.webm" %>" type="video/webm" />
          <source src="<%= asset_path "pet.ogv" %>" type="video/ogg" />
      </video>
  </div>
</section>

<!-- Poppy Cares! -->
<section id="we-care">
  <div id="poppy-cares">
    <h1>Poppy products think for you.</h1>
    <p>They work with Dash Replenishment Service by Amazon to reorder<br>the things that keep your household running smoothly.</p>
  </div>

  <div id="feature-boxes">
    <div class="width-wrapper">

      <div class="feature-box">
        <div class="feature-image-background">
          <%= image_tag "coffee.png", id: "coffee", alt: "coffee" %>
            <%= image_tag "coffee_1.png", id: "wing1", alt: "wing 1", class: "wow fadeIn", "data-wow-delay" => "0s" %>
            <%= image_tag "coffee_2.png", id: "wing2", alt: "wing 2", class: "wow fadeIn", "data-wow-delay" => ".5s" %>
            <%= image_tag "coffee_3.png", id: "wing3", alt: "wing 3", class: "wow fadeIn", "data-wow-delay" => "1s" %>
        </div>
        <div class="feature-box-text">
          <h2>Smart Sensors</h2>
          <p>Sensors know when it’s time to refill pet food, baby formula, coffee, filters, and more.</p>
        </div>
      </div>

      <div class="feature-box">
        <div class="feature-image-background">
          <%= image_tag "popup.png", id: "accio", alt: "dialog", class: "wow zoomIn", "data-wow-delay" => ".5s" %>
        </div>
        <div class="feature-box-text">
          <h2>Effortless Ordering</h2>
          <p>The products connect to your Amazon
          account to reorder your preferred brands.</p>
        </div>
      </div>

      <div class="feature-box">
        <div class="feature-image-background">
          <%= image_tag "amazon.png", id: "amazon", alt: "amazon", class: "wow fadeInDown", "data-wow-delay" => "1s" %>
        </div>
        <div class="feature-box-text">
          <h2>Automatic Delivery</h2>
          <p>Refills of exactly what you need are delivered just when you need them.</p>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- Remote Control -->
<section id="remote-control">
  <div id="slider">

    <div class="slide1">
      <div class="width-wrapper">
        <div class="slide-text">
          <h1>Hello, connected home.</h1>
          <p>Poppy products connect to the Wink app<br>
          so you can control, monitor, or schedule them from anywhere.</p>
        </div>
        <div class="slide-hand">
          <%= image_tag "hand_1.jpg" %>
        </div>
        <%= image_tag "pourover_blur.jpg", id: "trash", alt: "pour-over blur" %>
      </div>
    </div>

    <div class="slide2">
      <div class="width-wrapper">
        <div class="slide-text">
          <h1>Hello, connected home.</h1>
          <p>Poppy products connect to the Wink app<br>
          so you can control, monitor, or schedule them from anywhere.</p>
        </div>
        <div class="slide-hand">
          <%= image_tag "hand_2.jpg" %>
        </div>
        <%= image_tag "formula_blur.jpg", id: "trash", alt: "formula blur" %>
      </div>
    </div>

    <div class="slide3">
      <div class="width-wrapper">
        <div class="slide-text">
          <h1>Hello, connected home.</h1>
          <p>Poppy products connect to the Wink app<br>
          so you can control, monitor, or schedule them from anywhere.</p>
        </div>
        <div class="slide-hand">
          <%= image_tag "hand_3.jpg" %>
        </div>
        <%= image_tag "trash_blur.jpg", id: "trash", alt: "trash blur" %>
      </div>
    </div>


  </div>
</section>


<script src="https://f.vimeocdn.com/js/froogaloop2.min.js"></script>
<script>

var isSafari = Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0; 
if(isSafari == true) { 
  $('#pet-h').css('background-color', '#2f2f31');
  $('#pour-over-h').css('background-color', '#2f2f31');  
}

$(document).ready(function(){
  $(".width").fitVids();
});

var iframe = $('#pop')[0];
var player = $f(iframe);


$('.play-icon').click(function(){
  $('.popup-video').css('left', 0)
  $('.popup-video').addClass('pop-fade-in')
  player.api("play");
})

$('#close-popup, .popup-video').click(function(){
  $('.popup-video').removeClass('pop-fade-in')
  setTimeout(function() {
  $('.popup-video').css('left', '-100%')
  }, 300);
      player.api('pause');

})


</script>

app/views/home/pet.html.erb
<script type="text/javascript">
  init_product_js();
</script>

<header id="pet-header" class="product-header">
  <div class="product-width">
      <a href="<%= root_path %>"><%= image_tag('poppy.png', alt: 'poppy logo', class: 'animated fadeIn', id: 'nav-logo') %></a>
  </div>

  <a id="mobile-menu-3"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30.8 20"><path d="M30,18.5H0.8c-0.5,0-0.8,0.3-0.8,0.8C0,19.7,0.3,20,0.8,20H30c0.5,0,0.8-0.3,0.8-0.8C30.8,18.8,30.5,18.5,30,18.5z"/><path d="M0.8,1.5H30c0.5,0,0.8-0.3,0.8-0.8S30.5,0,30,0H0.8C0.3,0,0,0.3,0,0.8S0.3,1.5,0.8,1.5z"/><path d="M30,9.2H0.8C0.3,9.2,0,9.5,0,10c0,0.5,0.3,0.8,0.8,0.8H30c0.5,0,0.8-0.3,0.8-0.8C30.8,9.5,30.5,9.2,30,9.2z"/></svg></a>

  <div class="center-it animated fadeIn">
    <h1>Pet</h1>
    <h2>smart pet feeder</h2>
  </div>
  <%= image_tag('down.png', alt: 'down arrows', class: 'down animated fadeIn', id: '') %>
</header>

<div id="iphone" class="feature feature-odd">
  <div class="product-width">
    <div class="feature-text">
      <p>With Poppy Pet, you can monitor your pet’s eating habits, remotely schedule feedings, and dispense perfectly portioned meals with the Wink app.</p>
      <p>Get automatic refills on your favorite pet food delivered by Amazon when the machine detects that you’re running low.</p>
    </div>
    <div class="feature-image">
      <%= image_tag('product_iphone.png', alt: 'iphone', class: '', id: '') %>
      <div id="screen-slides">
        <%= image_tag('pet/p1_screen.jpg', alt: 'app screenshot', class: '', id: '') %>
        <%= image_tag('pet/p2_screen.jpg', alt: 'app screenshot', class: '', id: '') %>

      </div>
    </div>
  </div>
</div>

<div id="cat" class="feature feature-even">
  <div class="product-width">
    <div class="feature-text">
      <p>Its locking lid and weighted base safeguard food, making it great for large-breed dogs and stealthy cats.</p>
    </div>
    <div class="feature-image">
      <%= image_tag('pet/cat.jpg', alt: 'cat', class: '', id: '') %>
    </div>
  </div>
</div>

<div id="dog" class="feature feature-odd">
  <div class="product-width">
    <div class="feature-text">
      <p>The modern design looks like it actually belongs in your home, not your garage.</p>
    </div>
    <div class="feature-image">
      <%= image_tag('pet/dog_up.jpg', alt: 'dog up', class: '', id: '') %>
    </div>
  </div>
</div>

<div id="app-user" class="feature feature-even">
  <div class="product-width">
    <div class="feature-text">
      <p>Its storage bin holds 20 pounds of dry food discreetly, and a sensor tells you when the bowl is empty or if it’s been knocked over.</p>
    </div>
    <div class="feature-image">
      <%= image_tag('pet/app_user.jpg', alt: 'app user', class: '', id: '') %>
    </div>
  </div>
</div>

<div id="full-pet-image"></div>

<div id="machine">
  <%= image_tag('pet/machine.png', alt: 'pet feeder', class: 'machine-base', id: 'pet-base') %>

     <div id="pf1" class="plus">
      <span class="plus-icon animated infinite pulse">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M13.000,8.000 C13.000,8.000 8.000,8.000 8.000,8.000 C8.000,8.000 8.000,13.000 8.000,13.000 C8.000,13.552 7.552,14.000 7.000,14.000 C6.448,14.000 6.000,13.552 6.000,13.000 C6.000,13.000 6.000,8.000 6.000,8.000 C6.000,8.000 1.000,8.000 1.000,8.000 C0.448,8.000 -0.000,7.552 -0.000,7.000 C-0.000,6.448 0.448,6.000 1.000,6.000 C1.000,6.000 6.000,6.000 6.000,6.000 C6.000,6.000 6.000,1.000 6.000,1.000 C6.000,0.448 6.448,-0.000 7.000,-0.000 C7.552,-0.000 8.000,0.448 8.000,1.000 C8.000,1.000 8.000,6.000 8.000,6.000 C8.000,6.000 13.000,6.000 13.000,6.000 C13.552,6.000 14.000,6.448 14.000,7.000 C14.000,7.552 13.552,8.000 13.000,8.000 Z" id="path-1" class="cls-2" fill-rule="evenodd"/></svg>
      </span>
      <div class="line"></div>
        <p>Locking lid and weighted base safeguard food</p>
     </div>

     <div id="pf2" class="plus">
       <span class="plus-icon animated infinite pulse">
       <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M13.000,8.000 C13.000,8.000 8.000,8.000 8.000,8.000 C8.000,8.000 8.000,13.000 8.000,13.000 C8.000,13.552 7.552,14.000 7.000,14.000 C6.448,14.000 6.000,13.552 6.000,13.000 C6.000,13.000 6.000,8.000 6.000,8.000 C6.000,8.000 1.000,8.000 1.000,8.000 C0.448,8.000 -0.000,7.552 -0.000,7.000 C-0.000,6.448 0.448,6.000 1.000,6.000 C1.000,6.000 6.000,6.000 6.000,6.000 C6.000,6.000 6.000,1.000 6.000,1.000 C6.000,0.448 6.448,-0.000 7.000,-0.000 C7.552,-0.000 8.000,0.448 8.000,1.000 C8.000,1.000 8.000,6.000 8.000,6.000 C8.000,6.000 13.000,6.000 13.000,6.000 C13.552,6.000 14.000,6.448 14.000,7.000 C14.000,7.552 13.552,8.000 13.000,8.000 Z" id="path-1" class="cls-2" fill-rule="evenodd"/></svg>
       </span>
      <div class="line"></div>
      <p>Holds 20 pounds of dry pet food discretely (a standard bag size)</p>
     </div>

     <div id="pf3" class="plus">
       <span class="plus-icon animated infinite pulse">
       <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M13.000,8.000 C13.000,8.000 8.000,8.000 8.000,8.000 C8.000,8.000 8.000,13.000 8.000,13.000 C8.000,13.552 7.552,14.000 7.000,14.000 C6.448,14.000 6.000,13.552 6.000,13.000 C6.000,13.000 6.000,8.000 6.000,8.000 C6.000,8.000 1.000,8.000 1.000,8.000 C0.448,8.000 -0.000,7.552 -0.000,7.000 C-0.000,6.448 0.448,6.000 1.000,6.000 C1.000,6.000 6.000,6.000 6.000,6.000 C6.000,6.000 6.000,1.000 6.000,1.000 C6.000,0.448 6.448,-0.000 7.000,-0.000 C7.552,-0.000 8.000,0.448 8.000,1.000 C8.000,1.000 8.000,6.000 8.000,6.000 C8.000,6.000 13.000,6.000 13.000,6.000 C13.552,6.000 14.000,6.448 14.000,7.000 C14.000,7.552 13.552,8.000 13.000,8.000 Z" id="path-1" class="cls-2" fill-rule="evenodd"/></svg>
       </span>
      <div class="line"></div>
      <p>Great for dogs and cats of all sizes</p>
     </div>

     <div id="pf4" class="plus">
       <span class="plus-icon animated infinite pulse">
       <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M13.000,8.000 C13.000,8.000 8.000,8.000 8.000,8.000 C8.000,8.000 8.000,13.000 8.000,13.000 C8.000,13.552 7.552,14.000 7.000,14.000 C6.448,14.000 6.000,13.552 6.000,13.000 C6.000,13.000 6.000,8.000 6.000,8.000 C6.000,8.000 1.000,8.000 1.000,8.000 C0.448,8.000 -0.000,7.552 -0.000,7.000 C-0.000,6.448 0.448,6.000 1.000,6.000 C1.000,6.000 6.000,6.000 6.000,6.000 C6.000,6.000 6.000,1.000 6.000,1.000 C6.000,0.448 6.448,-0.000 7.000,-0.000 C7.552,-0.000 8.000,0.448 8.000,1.000 C8.000,1.000 8.000,6.000 8.000,6.000 C8.000,6.000 13.000,6.000 13.000,6.000 C13.552,6.000 14.000,6.448 14.000,7.000 C14.000,7.552 13.552,8.000 13.000,8.000 Z" id="path-1" class="cls-2" fill-rule="evenodd"/></svg>
       </span>
      <div class="line"></div>
      <p>Sensor tells you when bowl is empty or if it’s been knocked over</p>
     </div>

  <div id="form-m-top" class="machine-top">
  </div>
  <div id="machine-bottom">
    <div class="product-width">

    <div id="inventor">
      <div id="inventor-photo">
        <%= image_tag('pet/inventor.jpg', alt: 'inventor', class: '', id: '') %>
      </div>
      <div id="inventor-right">
        <h2>Invented by Chris Becker, a UI/UX designer from West Bend, WI</h2>
        <p>Chris wanted to help his portly dogs lose weight. Smaller, more frequent meals were an option, but his schedule got in the way. So he invented a way to feed his pooches any time, from anywhere.</p>
      </div>
    </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="Make Coffee">
  <title>Poppy - <%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= action_name %>">
  <!-- Navigation -->
  <% nav_wrapping_id = current_page?(root_path) ? "" : "product-nav-width" %>
  <% nav_wrapping_class = current_page?(root_path) ? "" : "product-width" %>
  <div id="<%= nav_wrapping_id %>" class="<%= nav_wrapping_class %>">
    <nav class="animated fadeIn" id="<%= current_page?(root_path) ? "master-navigation" : "product-navigation" %>">
      <ul>
        <li><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= root_path %>#about" class="scroll" data-hash="about" data-scroll-to="our-products">About</a></li>
        <li><a href="<%= root_path %>#products" class="scroll" data-hash="products" data-scroll-to="product-scroll-target">Products</a></li>
        <li><a href="<%= root_path %>#how-it-works" class="scroll" data-hash="how-it-works" data-scroll-to="we-care">How&nbsp;It&nbsp;Works</a></li>
        <li><a href="<%= root_path %>#sign-up"  class="scroll" data-hash="sign-up" data-scroll-to="footer-email">Sign&nbsp;Up</a></li>
      </ul>
    </nav>
  </div>

  <div id="fixed-nav">
    <div class="product-width">
      <a href="<%= root_path %>">
        <%= image_tag "poppy.png", alt: "poppy logo", id: "nav-logo" %>
      </a>

      <a id="mobile-menu-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30.8 20"><path d="M30,18.5H0.8c-0.5,0-0.8,0.3-0.8,0.8C0,19.7,0.3,20,0.8,20H30c0.5,0,0.8-0.3,0.8-0.8C30.8,18.8,30.5,18.5,30,18.5z"/><path d="M0.8,1.5H30c0.5,0,0.8-0.3,0.8-0.8S30.5,0,30,0H0.8C0.3,0,0,0.3,0,0.8S0.3,1.5,0.8,1.5z"/><path d="M30,9.2H0.8C0.3,9.2,0,9.5,0,10c0,0.5,0.3,0.8,0.8,0.8H30c0.5,0,0.8-0.3,0.8-0.8C30.8,9.5,30.5,9.2,30,9.2z"/></svg></a>

      <ul>
        <li><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= root_path %>#about" class="scroll" data-hash="about" data-scroll-to="our-products">About</a></li>
        <li><a href="<%= root_path %>#products" class="scroll" data-hash="products" data-scroll-to="product-scroll-target">Products</a></li>
        <li><a href="<%= root_path %>#how-it-works" class="scroll" data-hash="how-it-works" data-scroll-to="we-care">How&nbsp;It&nbsp;Works</a></li>
        <li><a href="<%= root_path %>#sign-up"  class="scroll" data-hash="sign-up" data-scroll-to="footer-email">Sign&nbsp;Up</a></li>
      </ul>

    </div>
  </div>

  <!-- Content -->
  <%= yield %>

  <!-- Footer -->
  <footer id="#master-footer">

    <div id="footer-email">
      <div class="width-wrapper cf">

        <div id="footer-left">
          <h2 class="default">Want to know when you can shop Poppy?<br>
          Enter your e-mail address below.</h2>

          <div id="email-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="42px"viewBox="0 0 34 26.2"><polygon points="34,5 11.2,26.2 11.1,26 6.6,21.2 0,14.1 4.9,9.6 11.5,16.7 29.4,0 "/></svg>
            <h2>Great, you're on the list!</h2>
            <p>We'll let you known when Poppy appliances are available</p>
          </div>

          <form id="email-form">
            <input id="email-input" type="email" placeholder="you@email.com">
            <button id="email-submit" value=""></button>
          </form>

          <p id="email-error">Hmm, that e-mail address doesn't look right</p>

        </div>

        <%= image_tag "footer/three-products.jpg", id: "footer-products" %>

      </div>
    </div>

    <div id="interested">
      <div class="product-width">
        <h2>Interested in working with us? We'd love to hear from you.</h2>
        <a href="mailto:partners@poppyhome.com">partners@poppyhome.com</a>
      </div>
    </div>

    <div id="footer-bottom">
      <div class="width-wrapper">
        <%= image_tag "poppy.png", id: "poppy-logo-footer" %>

        <ul>
          <li><a href="<%= legal_path %>">Legal</a></li>
          <li><a href="http://quirky.com">Quirky</a></li>
          <li><a href="http://wink.com">Wink</a></li>
          <li><a href="http://www.amazon.com/dashreplenishmentservice">Amazon</a></li>
        </ul>

      </div>
    </div>
  </footer>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-3535636-21', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>